### PR TITLE
updated vue template compiler version

### PR DESCRIPTION
**Pull request by rejifald**
#82

### CODE REVIEW

**Comment by nvms** [comment]
in a clean project, after a `yarn install`, I can no longer `yarn serve` this project:

output of `npm list | grep vue`:
```bash
vue-atlas git:(update-vue-compiler) ✗ npm list | grep vue
vue-atlas@2.0.10 /Users/pyers1/vue-atlas
├─┬ @vue/cli-plugin-babel@3.2.0
│ ├─┬ @vue/babel-preset-app@3.2.0
│ │ ├── babel-helper-vue-jsx-merge-props@2.0.3
│ │ ├─┬ babel-plugin-transform-vue-jsx@4.0.1
├─┬ @vue/cli-plugin-eslint@3.2.1
│ ├─┬ @vue/cli-shared-utils@3.2.0
│ ├─┬ eslint-plugin-vue@4.7.1
│ │ └─┬ vue-eslint-parser@2.0.3
├─┬ @vue/cli-plugin-unit-jest@3.2.0
│ ├── @vue/cli-shared-utils@3.2.0 deduped
│ ├─┬ jest-serializer-vue@2.0.2
│ └─┬ vue-jest@3.0.1
│   └── vue-template-es2015-compiler@1.6.0
├─┬ @vue/cli-service@3.2.0
npm│ ├── @vue/cli-overlay@3.2.0
│ ├── @vue/cli-shared-utils@3.2.0 deduped
│ ├── @vue/preload-webpack-plugin@1.1.0
│ ├── @vue/web-component-wrapper@1.2.0
 ERR! extraneous: node-pre-gyp@0.10.3 /Users/pyers1/vue-atlas/node_modules/node-pre-gyp
│ ├─┬ vue-loader@15.4.2
│ │ ├─┬ @vue/component-compiler-utils@2.3.0
│ │ │ └── vue-template-es2015-compiler@1.6.0 deduped
│ │ ├── vue-hot-reload-api@2.3.1
│ │ └─┬ vue-style-loader@4.1.2
├─┬ @vue/eslint-config-standard@4.0.0
├─┬ @vue/test-utils@1.0.0-beta.26
├─┬ eslint-plugin-vue@5.0.0
│ └─┬ vue-eslint-parser@4.0.3
├── vue@2.6.3
├── vue-router@3.0.2
└─┬ vue-template-compiler@2.6.6
```

the error:

```bash
Module build failed (from ./node_modules/vue-loader/lib/index.js):
Error: [vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
    at loadTemplateCompiler (/Users/pyers1/vue-atlas/node_modules/vue-loader/lib/index.js:21:11)
    at Object.module.exports (/Users/pyers1/vue-atlas/node_modules/vue-loader/lib/index.js:65:35)
```

**Comment by rejifald** [comment]
Damn. I used npm. Seems like it works different for u and me.

**Comment by rejifald** [comment]
Are u able to install and serve this project even without this PR ?

**Comment by rejifald** [comment]
I used to able serve project too, but on my own fork of project it doesn't work. I think it's because vue version installed with my fork is newer. Because there not strict version "^2.6.3", meanwhile template compiler has locked version.

**Comment by rejifald** [comment]
Provided new PR. I am closing this one.

**Pull request closed without merging**
