### PR TITLE
Allow to use complex values in Select component. #129

### PR DESCRIPTION
**Pull request by max-frai**
Fix for #129. This allows to use object keys in Select component.

### CODE REVIEW

**Comment by nvms** [comment]
I approve this change but will need to resolve this merge conflict. It's not immediately clear to me why this conflict is happening. I'm looking into it.

**Comment by nvms** [comment]
so it looks like your master is a ways behind my master, hence the conflict. I will push a commit shortly, adding your changes from this PR and also the changes for issue #119

**Comment by max-frai** [comment]
It's so strange, I cloned your repo from scratch. Thank you very much.

**Comment by nvms** [comment]
please see commit f1573dc where your changes have been added. thank you.

I regret not being able to merge this due to a strange conflict

**Pull request closed without merging**
