### PR TITLE
File picker

### PR DESCRIPTION
**Pull request by rejifald**
**What kind of changes does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes:
- [ ] Other,please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If adding a **new feature**, the PR's description includes:
- [[#47]](https://github.com/nvms/vue-atlas/issues/47) A convincing reason for adding this feature

### CODE REVIEW

**Comment by nvms** [comment]
it's an awesome start, for sure! without knowing where exactly you are trying to end up with this, here are some suggestions and implementation details that I'd like to see:

- follow the same SCSS implementation as all other components:
  - create an scss file in `/src/style` for the component, and import it into `/src/style/_common.scss` along with the rest of the stylesheets
  - where possible, avoid using hard-coded color values and instead please try to use the colors defined in `/src/style/_colors.scss`
- ideally, this would be implemented as a different input type so that it can be referenced like this: `<va-input type="file" />`
- maybe make use of the `loading` prop that the VaButton while the upload is actually happening so that there is some feedback that it's being uploaded
- for long file names, maybe you could set the filename's text-overflow to ellipsis so that they don't end up wrapping like this:

screen shot 2019-02-22 at 10 25 30 am

- for now, please use the same `classPrefix` prop that all other components use to reference class styles:

```javascript
props: {
  classPrefix: {
    type: String,
    default: 'va'
  }
}
```
```html
<div :class="`${classPrefix}-file-picker_wrapper`">
```

issues:
- when `multiple` is passed and I upload two items **at the same time**, they both appear under the upload button as such:
screen shot 2019-02-22 at 10 07 47 am

then, when I try to upload a third item, I would expect to see it appear in the list alongside the other two, but instead of appending it, the list is modified to include only the third item:

screen shot 2019-02-22 at 10 25 17 am

**Comment by nvms** [comment]
I should add: it's very minimalistic and elegant so far. I like that.

**Comment by rejifald** [comment]
> follow the same SCSS implementation as all other components:
Will do
> ideally, this would be implemented as a different input type
Yes, that what i suggested before. I assume that u will replace va-input component with something like that
```
<FilePicker v-if="type === 'file'"/>
<DatePicker v-if="type === 'date'"/>
...
```
> maybe make use of the `loading` prop
will do
> for long file names
will do
> when `multiple` is passed
this is standard input behavior. In this case, files can be added, for sure. Because in this implementation user has ability to remove any of them.
Also i don't know where show file preview.
I think list items can be replaced by collapse item, and preview will be inside.

**Comment by rejifald** [comment]
BTW, in this case, button should have icon either at the left, or at the right. WDYT ?

**Comment by rejifald** [comment]
And probably somewhere should be "clear" button. WDYT ?

**Comment by nvms** [comment]
> I think list items can be replaced by collapse item, and preview will be inside.

great idea.. for any file type, you can hide the file details inside of a closed collapse panel

> BTW, in this case, button should have icon either at the left, or at the right. WDYT ?

my initial thought would be to place the icon on the right side. I'm working on the prefix/postfix solution so that it'll look nicer later on.

> And probably somewhere should be "clear" button. WDYT ?

can you elaborate on this?

> this is standard input behavior. In this case, files can be added, for sure. Because in this implementation user has ability to remove any of them.

yes, and I **like** the fact that both appear. this is good. _however_, when I upload an additional item, I would expect that it appears in the list below, **along with** the other items that have already been uploaded. I hope that makes sense

```html
<FilePicker v-if="type === 'file'"/>
<DatePicker v-if="type === 'date'"/>
```

I see. that makes perfect sense.

**Comment by rejifald** [comment]
> for long file names, maybe you could set the filename's text-overflow to ellipsis so that they don't end up wrapping like this:
Maybe it should be implemented in button component itself ? WDYT ?
> create an scss file in `/src/style` for the component, and import it into `/src/style/_common.scss` along with the rest of the stylesheets
I see there a few files, but most of them isn't exists in there.
Also, it makes Tree Shacking impossible.
I mean, if i will include styles for this component only into `_common.scss`.
-------
Other remarks i`ve fixed.

**Comment by rejifald** [comment]
And... I found that there no way how detect when loading is started and when is ended. File input fires only two events. `input` and `change`. They fires with 2ms difference. 
Any ideas ?

**Comment by nvms** [comment]
> > create an scss file in `/src/style` for the component, and import it into `/src/style/_common.scss` along with the rest of the stylesheets

> I see there a few files, but most of them isn't exists in there.
Also, it makes Tree Shacking impossible.
I mean, if i will include styles for this component only into `_common.scss`.

in commit bd61ddb, component styles were moved into their .vue parent file, a chore that I've been meaning to do for a while. sorry, forgot to mention that in this PR afterwards.

> > for long file names, maybe you could set the filename's text-overflow to ellipsis so that they don't end up wrapping like this:

> Maybe it should be implemented in button component itself ? WDYT ?

good idea

**Comment by rejifald** [comment]
Great ! 
I also want to discuss with u classPrefix prop. Why it's needed ?
It overloads template visually, and also the Vue needs to evaluate class property as JS statement every time... But, what it's advantages ?

**Comment by nvms** [comment]
that's also a chore on my list of things I need to get rid of

it was implemented from the beginning with the idea that classes can be easily overridden by just changing the class prefix. I realized long ago that it is a bad idea, but if I'm going to start getting rid of it, then it needs to be removed everywhere

you can go ahead and not use it. I may have this removed by the time you're finished

**Comment by rejifald** [comment]
Therefore i need also decide whatever i should do with button loading.
I see no idea how implement this.
I also tried choose large and small files. Seems like there no difference between movie and plain picture. 
But biggest problem here for my opinion, is the fact, that i can't know when user just clicked "cancel" in opened window. And therefore i can't disable "loading" on button.

**Comment by nvms** [comment]
> that i can't know when user just clicked "cancel" in opened window. And therefore i can't disable "loading" on button.

try checking `event.target.files` for the `change` event, something like this:

```javascript
onChange (e) {
  let files = e.target.files // files is FileList object
  // check the length of files to see if
  // anything was selected
}
```

https://webplatform.github.io/docs/apis/file/FileList/

**Comment by rejifald** [comment]
> try checking `event.target.files` for the `change` event, something like this:
Problem is that event won't be fired if u clicked "cancel".

**Comment by rejifald** [comment]
I updated PR

**Comment by nvms** [comment]
I looked at it. it is coming along nicely.

**Comment by rejifald** [comment]
Is it ok already ? Or not yet ?

**Comment by nvms** [comment]
do you think you could provide a quick usage example in the provided App.vue? just so I'm clear on intended usage within a form, etc.

**Pull request merged**
